[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/hcl2"
  branch = "master"

[[constraint]]
  branch = "plugins"
  name = "github.com/wata727/tflint"
  source = "github.com/howdoicomputer/tflint"

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "=v0.12.0-alpha2"

[prune]
  go-tests = true
  unused-packages = true
